import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "../components/ui/theme-provider";
import React, { ReactNode } from "react";
import { AuthProvider } from "./Providers";
import { Toaster } from "react-hot-toast";

interface RootLayoutProps {
  children: ReactNode; // Define the type for children prop
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children} {/* Render the children components */}
          </ThemeProvider>
          <Toaster /> {/* Include Toaster for notifications */}
        </AuthProvider>
      </body>
    </html>
  );
}

// Local font configuration
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
